# Define databases configuration
dbs:
  mysql-01:
    type: mysql
    ip: localhost
    port: 3306
    user: leo
    passwd: leo130

kafkas:
  server:
    host: localhost 
    port: 9092

  producer:
    maxProducer: 3
 
  consumer:
    maxConsumer: 10